//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaPresentacion
    {
        public int Id { get; set; }
        public Nullable<int> EventoId { get; set; }
        public Nullable<int> EmprendimientoId { get; set; }
        public Nullable<System.TimeSpan> HoraComienzo { get; set; }
        public Nullable<System.TimeSpan> HoraSalida { get; set; }
        public Nullable<int> OrdenPresentacion { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
