//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.AgendaPresentacions = new HashSet<AgendaPresentacion>();
        }
    
        public int Id { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> OrdenPresentacion { get; set; }
        public System.DateTime FechaPresentacion { get; set; }
        public System.TimeSpan HoraComienzo { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public string NombreEvento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendaPresentacion> AgendaPresentacions { get; set; }
    }
}
