//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int Id { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> OrdenPresentacion { get; set; }
        public int EmprendimientoId { get; set; }
    
        public virtual Emprendimiento Emprendimiento { get; set; }
    }
}
