//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Cargo { get; set; }
        public string FotoUrl { get; set; }
        public int? EmprendimientoId { get; set; }
    
        public virtual Emprendimiento Emprendimiento { get; set; }
    }
}
