//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotosPublico
    {
        public int Id { get; set; }
        public int EmprendimientoId { get; set; }
        public int CategoriaPremiacionId { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Comentario { get; set; }
    
        public virtual CategoriasPremiacion CategoriasPremiacion { get; set; }
        public virtual Emprendimiento Emprendimiento { get; set; }
    }
}
